packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalogs:
  cli:
    '@antfu/eslint-config': ^5.2.1
    '@antfu/ni': ^25.0.0
    '@changesets/cli': ^2.29.6
    '@commitlint/cli': ^19.8.1
    '@commitlint/config-conventional': ^19.8.1
    '@commitlint/types': ^19.8.1
    eslint: ^9.34.0
    husky: ^9.1.7
    lint-staged: ^16.1.6
    tsx: ^4.20.5
    typescript: ^5.9.2
    unbuild: ^3.6.1
    vite: ^7.1.4
  inlined:
    '@antfu/utils': ^9.2.0
  testing:
    vitest: ^3.2.4
    vitest-package-exports: ^0.1.1
    yaml: ^2.8.1
  types:
    '@types/node': ^22.18.0
  utils:
    tinyexec: ^1.0.1
onlyBuiltDependencies: []
